# Generated by Django 4.1.5 on 2023-01-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cust',
            table='customer',
        ),
    ]
