# Generated by Django 4.1.5 on 2023-01-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_cust_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust',
            name='cust_phn',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
