# Generated by Django 4.1.5 on 2023-01-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_cust_cust_phn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust',
            name='cust_email',
            field=models.CharField(max_length=50),
        ),
    ]
