# Generated by Django 4.1.5 on 2023-01-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_cust_cust_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_fname', models.CharField(max_length=20)),
                ('seller_lname', models.CharField(max_length=20)),
                ('seller_email', models.CharField(max_length=50)),
                ('seller_phn', models.BigIntegerField()),
                ('seller_pass', models.CharField(max_length=40)),
                ('seller_bus', models.CharField(max_length=40)),
                ('bank', models.CharField(max_length=40)),
                ('seller_accnt', models.BigIntegerField()),
                ('seller_image', models.ImageField(upload_to='seller/')),
            ],
        ),
    ]
