# Generated by Django 4.1.5 on 2023-01-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_seller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
    ]
