# Generated by Django 4.1.5 on 2023-01-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_seller_seller_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(default='approved', max_length=20),
        ),
    ]
