# Generated by Django 4.1.5 on 2023-01-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
