# Generated by Django 4.1.5 on 2023-01-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protitle', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('proid', models.IntegerField()),
                ('prosubtitle', models.CharField(max_length=40)),
                ('proimg', models.ImageField(upload_to='product/')),
                ('price', models.IntegerField()),
                ('prodesc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
