# Generated by Django 4.1.5 on 2023-01-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0002_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default='1'),
        ),
    ]
