# Generated by Django 4.1.5 on 2023-01-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spyderadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'spyderadmin',
            },
        ),
    ]
