# Generated by Django 4.1.5 on 2023-01-11 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0007_seller_seller_usr'),
        ('reseller', '0002_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cust')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller.product')),
            ],
        ),
    ]
